FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y mysql-server python3 python3-pip
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

COPY . /app
WORKDIR /app

RUN pip3 install -r requirements.txt

RUN chmod +x entrypoint.sh

EXPOSE 5080

ENTRYPOINT ["./entrypoint.sh"]
